
<?$APPLICATION->IncludeComponent(
    "bitrix:news.detail",
    "services_custom_pyro",
    Array(
        "LIST_PRODUCT_BLOCKS_ORDER" => ($arParams["LIST_PRODUCT_BLOCKS_ORDER"] ? $arParams["LIST_PRODUCT_BLOCKS_ORDER"] : "tizers,sale,tab,gallery,comments,brand,services,goods,partners,reviews,staff,vacancys,sertificates"),
        "LIST_PRODUCT_BLOCKS_TAB_ORDER" => ($arParams["LIST_PRODUCT_BLOCKS_TAB_ORDER"] ? $arParams["LIST_PRODUCT_BLOCKS_TAB_ORDER"] : "tarifs,desc,char,projects,faq,docs,video"),
        "SERVICES_LINK_ELEMENTS_TEMPLATE" => $arParams["SERVICES_LINK_ELEMENTS_TEMPLATE"],
        "FORM_ID_ORDER_SERVISE" => $arParams["FORM_ID_ORDER_SERVISE"],
        "ORDER_VIEW" => $bOrderViewBasket,
        "DISPLAY_DATE" => $arParams["DISPLAY_DATE"],
        "DISPLAY_NAME" => $arParams["DISPLAY_NAME"],
        "DISPLAY_PICTURE" => $arParams["DISPLAY_PICTURE"],
        "DISPLAY_PREVIEW_TEXT" => $arParams["DISPLAY_PREVIEW_TEXT"],
        "IBLOCK_TYPE" => $arParams["IBLOCK_TYPE"],
        "IBLOCK_ID" => $arParams["IBLOCK_ID"],
        "FIELD_CODE" => $arParams["DETAIL_FIELD_CODE"],
        "PROPERTY_CODE" => $arParams["DETAIL_PROPERTY_CODE"],
        "DETAIL_URL"	=>	$arResult["FOLDER"].$arResult["URL_TEMPLATES"]["detail"],
        "SECTION_URL"	=>	$arResult["FOLDER"].$arResult["URL_TEMPLATES"]["section"],
        "META_KEYWORDS" => $arParams["META_KEYWORDS"],
        "META_DESCRIPTION" => $arParams["META_DESCRIPTION"],
        "BROWSER_TITLE" => $arParams["BROWSER_TITLE"],
        "DISPLAY_PANEL" => $arParams["DISPLAY_PANEL"],
        "SET_CANONICAL_URL" => $arParams["DETAIL_SET_CANONICAL_URL"],
        "SET_TITLE" => $arParams["SET_TITLE"],
        "SET_STATUS_404" => $arParams["SET_STATUS_404"],
        "CACHE_TYPE" => $arParams["CACHE_TYPE"],
        "CACHE_TIME" => $arParams["CACHE_TIME"],
        "CACHE_GROUPS" => $arParams["CACHE_GROUPS"],
        "USE_PERMISSIONS" => $arParams["USE_PERMISSIONS"],
        "GROUP_PERMISSIONS" => $arParams["GROUP_PERMISSIONS"],
        "REVIEWS_IBLOCK_ID" => $arParams["REVIEWS_IBLOCK_ID"],
        "PROJECTS_IBLOCK_ID" => $arParams["PROJECTS_IBLOCK_ID"],
        "SERVICES_IBLOCK_ID" => $arParams["SERVICES_IBLOCK_ID"],
        "CATALOG_IBLOCK_ID" => $arParams["CATALOG_IBLOCK_ID"],
        "STAFF_IBLOCK_ID" => $arParams["STAFF_IBLOCK_ID"],
        "PARTNERS_IBLOCK_ID" => $arParams["PARTNERS_IBLOCK_ID"],
        "NEWS_IBLOCK_ID" => $arParams["NEWS_IBLOCK_ID"],
        "FAQ_IBLOCK_ID" => $arParams["FAQ_IBLOCK_ID"],
        "VACANCYS_IBLOCK_ID" => $arParams["VACANCYS_IBLOCK_ID"],
        "SERTIFICATES_IBLOCK_ID" => $arParams["SERTIFICATES_IBLOCK_ID"],
        "COMMENTS_COUNT" => $arParams['COMMENTS_COUNT'],
        "DETAIL_USE_COMMENTS" => $arParams['DETAIL_USE_COMMENTS'],
        "ELEMENT_ID" => $arResult["VARIABLES"]["ELEMENT_ID"],
        "ELEMENT_CODE" => $arResult["VARIABLES"]["ELEMENT_CODE"],
        "IBLOCK_URL" => $arResult["FOLDER"].$arResult["URL_TEMPLATES"]["news"],
    ),
    $component
);?>